[application]
name = "kobrax"
title = "Kobrax"
version = "package.json::version"
organization = "Kobra Network"

[description]
short = "Desktop Node and Wallet for Kobra"
long = """
Kobrax is a desktop wallet and a p2p network node instance. This
application allows you to participate in the Kobra network by running a
local node instance and offers access to a local wallet, compatible with
the web wallet available at https://wallet.k0bradag.com
"""

[package]
archive = { include = true }
signatures = ["SHA256"]
build = [
    { NPM = { clean = true } }
]
resources = "resources/setup"
output = "setup/$PLATFORM-$ARCH"
include = [
    { glob = [
            "bin/*",
            "*.js",
            "resources/**.css",
            "resources/images/*.*",
            "resources/**.ttf",
            "resources/**.woff",
            "resources/**.svg",
            "i18n.*",
            "modules/*",
            "lib/*",
            "node_modules/*",
            "package.json"
        ]},
]

[[action]]
items = [{ copy = { glob = [
        ".templates",
        ".defaults",
        "CHANGELOG.md"
    ], to = "$TARGET", hidden = true}}]

[[dependency]]
name = "kobrad"
git = { url = "https://github.com/kobradag/kobrad", branch = "master" }
run = [
    { cmd = "go build" },
    { cmd = "go build", cwd = "cmd/genkeypair" },
    { cmd = "go build", cwd = "cmd/kobractl" },
    { cmd = "go build", cwd = "cmd/kobrawallet" },
]
copy = [
    { regex = [
        "kobrad(.exe)?$",
        "genkeypair(.exe)?$",
        "kobractl(.exe)?$",
        "kobrawallet(.exe)?$",
    ], to = "bin/$PLATFORM-$ARCH", flatten = true },
]

[nwjs]
version = "0.78.1"
ffmpeg = false

[macos-disk-image]
window_caption_height = 60
window_position = [400,100]
window_size = [485,330]
icon_size = 72
application_icon_position = [100,158]
system_applications_folder_position = [385,158]

[windows]
uuid = "8d51c029-f5dc-44d8-b453-f93629fee7b7"
group = "Kobra"
run_after_setup = true

[images]
application="logo.png"
macos-application="Icon1024.png"
macos-disk-image="kobrax-dmg.png"
innosetup-icon="logo.png"
innosetup-wizard-small="kobrax-55x58.bmp"
innosetup-wizard-large="kobrax-164x314.bmp"

[languages]
languages = ["dutch", "english", "finnish", "french", "german", "italian", "polish", "portuguese", "russian", "spanish", "turkish", "ukranian"]

[firewall]
application = { direction = "in+out" }
rules = [
    { name = "Kobra Node", program = "bin/windows-x64/kobrad.exe", direction="in+out" }
]
